### ISSUE TITLE
Optional hashes in URL will autoplay songs

### ISSUE THREAD

**Issue by evangipson** [evangipson/limp#2]
Going to need to hook up songs w/ hashes somehow... then autoplaying the audio should be pretty trivial in JS.

**Comment by robertpateii** [comment]
came here to make sure autoplay was on the feature list!

id/hash/fragments for each song is a good idea too for shareability, but not _necessarily_ part of autoplay.  data("song-path") is already unique to each element. you also have the nodelist if you getElementsByClass("songList").

so it'd be like
```
if autoplay is on and a song ends
    determine next song
    play next song
```

But it looks like you randomize the order of songs on each load. Which means you must have some data structure of songs besides the HTML? ah here it is

```
shuffle($albumList);
shuffle($songTiles);
```

So yeah you could populate the song-next attribute serverside when you do the rest. if you add IDs to each song in PHP with something like ```ID="getID($songTiles[i])"``` then you do the same for ```song-next="getID($songTiles[i+1])"```

IDs is looking like the best approach because then "determine next song" and "play next song" can just be this:
```
var nextID = $(".active").data("song-next");
$("#"+nextID).click()
```

but you could just as well do this without IDs:
```
var nextID = $(".active").data("song-next-path");
$(".song[data-song-path='"+nextID+"']").click()
```

in a sense it's the same, the path is unique, the ID must be unique, you could programmatically assign an ID based on path in the PHP.

**Comment by robertpateii** [comment]
in other news, i'm surprised you didn't use vue for this. did you consider it but just want to do without for the sake of learning? Or was it not suited to some things you wanted to do?

**Comment by evangipson** [comment]
great write up about the autoplay!!! i still have to digest this.

other news: really using a whole framework seemed overkill. I just needed some VERY BASIC file traversal functionality, and didn't think using an entire mvc-light framework was way too much. I already knew some very basic PHP and as soon as I thought "server-side", I don't normally go to javascript (except for Vueture, which was a learning experiment).

**Comment by robertpateii** [comment]
if you're faster knocking out this php than spinning up another vue site then yeah, good call, getting this out the door in a weekend is a huge success.

A framework (be it vue or some php framework) though would be useful if you end up expanding this with a bunch of features. Ideally before you do all the work for those features. So it really depends what's all bubbling around in your head for this.

**Comment by robertpateii** [comment]
we talked about this

```
        $nextVisibleSong = $(".active").nextAll('.song:visible').first();
        $nextVisibleSong.length ? $nextVisibleSong.click() : $("#songList").find(".song:visible").first().click();
```

more readable and performant

**Comment by evangipson** [comment]
> more readable and performant

Done! https://github.com/evangipson/limp/commit/b3c1ef5098992db59f6548d3a5bbe861376a3947

**Comment by evangipson** [comment]
As far as the id/query string/hash sharing method, here's what I'm thinking:

Everytime a song is played, append some query string values to the URL, so that "sharing" is just copying the current URL to the clipboard for the user. Maybe add a right-click context option or like a "share" button?

As far as the actual query string params:
- Album Filter (if they've filtered, so the audience gets the same experience)
- Song
- Autoplay = true

**Comment by robertpateii** [comment]
sharing the "same experience" really means sharing the entire state of the music player. That would be cool, but i'd start with just making it possible to share an individual song. 

Keep in mind query strings = an actual URL that hits the server and fragment/hash = doesn't hit the server, but can be used by javascript. You would probably want to use query strings to represent the whole state, but again that's too much too soon. Phase 1: be able to share a song. Phase 2: depends on what people want next.

So that puts us back at your original idea!
1. Playing a song should put the song name in the URL bar as a fragment
    a. As you develop this you'll be forced to learn about fragments and navigation history. I'd do whatever is easier (update history or ignore history) since it's debatable if the back button should go to the last played song or not. personally I wouldn't want that, but again it's debatable. 
2. on dom ready, check if the fragment matches a song. if so, click() the song.

bam, now people can hear a song they like and link it to their friends or bookmark it.

=== on share ===
No to share buttons. Do you use share buttons? I don't use share buttons. Does anyone you know use share buttons instead of just linking the URL?

If the user is on a mobile phone, their browser has a built in share functionality which will use the URL.  Don't build a feature into your site that's already in the browser. (also you should rarely/never override right click functionality on a web page. if gmail didn't need to do that, you probably don't either.)

**Comment by robertpateii** [comment]
also since this isn't work, feel free at anytime to tell me to stop suggesting how **you** should build **your** program.

**Comment by evangipson** [comment]
no, no! i put this stuff on github for people to interface with me! if i didn't want to collaborate, i surely wouldn't have put this on github **_and_** told you where to find it!

in other words- keep it coming!!

**Comment by evangipson** [comment]
:D https://github.com/evangipson/limp/commit/9be61fdabf1efac808b511d849400048bd0b15da

**Comment by evangipson** [comment]
Was able to get state somewhat working as well, with little to no extra work because I was already keeping track of the album on each song tile via data attribute: https://github.com/evangipson/limp/commit/ac798022f8b23c1374dab01a892c72c596ccde3d

All I had to do was look for the nav element which had the "data-album-filter" attribute that matched and click it!

**Comment by evangipson** [comment]
proof it works! http://evangipson.com/music/#bXVzaWMvU3dhbXAgUGVvcGxlL3Zpb3IubXAz

after you test @robertpateii, i'll close!

**Comment by robertpateii** [comment]
cool! it does work http://evangipson.com/music/#bXVzaWMvTWlzY2VsbGFuZW91cyBVbnJlbGVhc2VkL3Byb3RvcGlhbm8ubXAz

you may want to not base64 encode them because
1. they're so long you can't tell they actually change when you click a song, especially on mobile
2. not human readable

Now that you're using path which is unique, i bet you could just use the URI Encode directly without running btoa over it.

If you wanted to be really slick, i bet you could take the path in PHP and chop it up into a good vanity unique ID that you could add as an ID to each rendered song element. I like the song name first so if you're on mobile the change is more easily visible as you listen to an album.

http://evangipson.com/music/#vior:swamp-people

the nice thing about fragments is they don't get sent to the server so you have more leeway than in the rest of the URL:
https://stackoverflow.com/questions/2053132/is-a-colon-safe-for-friendly-url-use

**Comment by robertpateii** [comment]
![screenshot_2017-10-11-02-54-32](https://user-images.githubusercontent.com/494069/31428284-eab36008-ae2f-11e7-80a2-3ee05e07c1be.png)

**Comment by evangipson** [comment]
It works! http://evangipson.com/music/#hbb-upbeat:hammerbomb

Even handles complicated cases with spaces, dashes, and parenthesis well: http://evangipson.com/music/#6th-song-exit-(fin):no-place-like-home

Also I put a line in there specifically to replace colons with dashes, as to not break my hash system.

Gonna close as this is working well now in  17196e9
